import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;

// NumberGame class to create a frame where user can play the game with some set of rules and hints
public class NumberGame extends JFrame implements ActionListener{
    int randomNumber;
    JButton exit, check;
    int round ;
    JTextField guessTextField;
    int chances = 5;
    int wins ;

    NumberGame(int round, int wins){
        this.round = round;
        this.wins = wins;
        setLayout(null);
        Random random = new Random();
        randomNumber = Math.abs((random.nextInt()%100))+1;
        setSize(800,700);
        setVisible(true);
        setBounds(300,20,800,700);
        setTitle("Random Number Guessing Game");

        JLabel text = new JLabel("Welcome To The Random Number Guessing Game");
        text.setFont(new Font("Railway",Font.BOLD,30));
        text.setBounds(40,30,750,35);
        add(text);

        JLabel rule = new JLabel("RULES:-");
        rule.setFont(new Font("Railway",Font.BOLD,16));
        rule.setBounds(40,100,100,20);
        add(rule);

        JLabel rule1 = new JLabel("1. Guess a number from 1 to 100.");
        rule1.setFont(new Font("Railway",Font.BOLD,14));
        rule1.setBounds(40,130,400,20);
        add(rule1);

        JLabel rule2 = new JLabel("2. Compare it with an automated random number generated by the computer.");
        rule2.setFont(new Font("Railway",Font.BOLD,14));
        rule2.setBounds(40,160,600,20);
        add(rule2);

        JLabel rule3 = new JLabel("3. You have only 5 chances to guess the correct number.");
        rule3.setFont(new Font("Railway",Font.BOLD,14));
        rule3.setBounds(40,190,600,20);
        add(rule3);

        JLabel rule4 = new JLabel("4. Guess accordinly to hints given, if the guess is wrong.");
        rule4.setFont(new Font("Railway",Font.BOLD,14));
        rule4.setBounds(40,220,500,20);
        add(rule4);

        JLabel hint1 = new JLabel("(i) 'Too high' means difference of the numbers is >10 , choose a lower number.");
        hint1.setFont(new Font("Railway",Font.BOLD,13));
        hint1.setBounds(60,245,600,20);
        add(hint1);

        JLabel hint2 = new JLabel("(ii) 'High' means difference of the numbers is <=10 , choose a lower number.");
        hint2.setFont(new Font("Railway",Font.BOLD,13));
        hint2.setBounds(60,265,600,20);
        add(hint2);

        JLabel hint3 = new JLabel("(iii) 'Too low' means difference of the numbers is >10 , choose a higher number.");
        hint3.setFont(new Font("Railway",Font.BOLD,13));
        hint3.setBounds(60,285,600,20);
        add(hint3);

        JLabel hint4 = new JLabel("(iv) 'Low' means difference of the numbers is <=10 , choose a higher number.");
        hint4.setFont(new Font("Railway",Font.BOLD,13));
        hint4.setBounds(60,305,600,20);
        add(hint4);

        JLabel roundNumber = new JLabel("**************************** ROUND "+round+" **************************");
        roundNumber.setFont(new Font("Railway",Font.BOLD,18));
        roundNumber.setBounds(40,350,700,20);
        add(roundNumber);

        JLabel guess = new JLabel("ENTER YOUR GUESS:");
        guess.setFont(new Font("Railway",Font.BOLD,24));
        guess.setBounds(40,400,270,30);
        add(guess);

        guessTextField = new JTextField();
        guessTextField.setFont(new Font("Railway",Font.BOLD,24));
        guessTextField.setBounds(320,400,120,40);
        add(guessTextField);

        exit = new JButton("EXIT");
        exit.setBackground(Color.BLACK);
        exit.setForeground(Color.WHITE);
        exit.setFont(new Font("Railway",Font.BOLD,16));
        exit.setBounds(40,470,120,35);
        add(exit);
        exit.addActionListener(this);

        check = new JButton("CHECK");
        check.setBackground(Color.BLACK);
        check.setForeground(Color.WHITE);
        check.setFont(new Font("Railway",Font.BOLD,16));
        check.setBounds(320,470,120,35);
        add(check);
        check.addActionListener(this);

    }
    // ActionListener for NumberGame class for exit and check buttons
    public void actionPerformed(ActionEvent ae){
        if(ae.getSource()==exit){
            JOptionPane.showMessageDialog(null,"If you exit you won't be able to play the game");
            System.exit(0);
        }
        // compare the guessed number to the random generated number and provide hints to the user
        else if(ae.getSource()==check){
            int guessedNumber = Integer.parseInt(guessTextField.getText());
            chances-=1;
            //User Wins by guessing the correct number
            if(guessedNumber==randomNumber){
                    JOptionPane.showMessageDialog(null,"Congratulations! You Won.");
                    ++wins;
                    setVisible(false);
                    new PlayAgain(round,wins).setVisible(true);

            }
            //User lose as not able to guess within 5 chances 
            else if(chances==0 ){
                    JOptionPane.showMessageDialog(null,"You Lose!");
                    setVisible(false);
                    new PlayAgain(round,wins).setVisible(true);
            }
            //Hint 1
            else if(Math.abs(guessedNumber-randomNumber)>10 && guessedNumber>randomNumber){
                    JOptionPane.showMessageDialog(null,"Too High and You have "+chances+" left");
            }
            // Hint 2    
            else if(Math.abs(guessedNumber-randomNumber)<=10 && guessedNumber>randomNumber){
                    JOptionPane.showMessageDialog(null,"High and You have "+chances+" left");
            }
            // Hint 3    
            else if((randomNumber-guessedNumber)>10){
                    JOptionPane.showMessageDialog(null,"Too Low and You have "+chances+" left");
            }
            //Hint 4
            else if((randomNumber-guessedNumber)<=10){
                    JOptionPane.showMessageDialog(null,"Low and You have "+chances+" left");
            }
        }
        
    }

    // this will create a initial frame of NumberGame class
    public static void main(String[] args){

        new NumberGame(1,0);
    }
    
}
// creating a new class to create a frame to ask if a user wants to play again or not
class PlayAgain extends JFrame implements ActionListener{
  JButton yes, no;
  int round;
  int wins;

  PlayAgain(int round, int wins){
        this.round = round;
        this.wins = wins;
        setLayout(null);
        setSize(500,200);
        setBounds(500,300,500,200);
        setVisible(true);
        
        JLabel play = new JLabel("Do you want to play again?");
        play.setFont(new Font("Railway",Font.BOLD,24));
        play.setBounds(90,40,400,30);
        add(play);

        yes = new JButton("YES");
        yes.setBackground(Color.BLACK);
        yes.setForeground(Color.WHITE);
        yes.setFont(new Font("Railway",Font.BOLD,14));
        yes.setBounds(90,100,120,30);
        add(yes);
        yes.addActionListener(this);

        no = new JButton("NO");
        no.setBackground(Color.BLACK);
        no.setForeground(Color.WHITE);
        no.setFont(new Font("Railway",Font.BOLD,14));
        no.setBounds(280,100,120,30);
        add(no);
        no.addActionListener(this);
  
    }
    // ActionListener for PlayAgain class for yes and no buttons
    public void actionPerformed(ActionEvent ae){
        // user will be able to play another round again 
        if(ae.getSource()==yes){
            setVisible(false);
            new NumberGame(++round,wins).setVisible(true);
        }
        //show the final score of user before exiting the game 
        else if(ae.getSource()==no){
           JOptionPane.showMessageDialog(null,"Your final score: "+wins+"/"+round);
           System.exit(0);
        }
            
    }
 }


